This notebook was prepared by Cayetano Benavent, 2016.

# Map Algebra with GDAL and NumPy

In [60]:
from osgeo import gdal

In [61]:
src_file01 = '../../data/temp_gfs/tmp_2m_k_20150903.tif'
src_file02 = '../../data/temp_gfs/tmp_80m_k_20150903.tif'

Read datasets:

In [62]:
src_ds01 = gdal.Open(src_file01)
src_ds02 = gdal.Open(src_file02)

In [63]:
src01_band = src_ds01.GetRasterBand(1)
src02_band = src_ds02.GetRasterBand(1)

Read bands as NumPy arrays:

In [64]:
src01_ar = src01_band.ReadAsArray()
src02_ar = src02_band.ReadAsArray()

In [65]:
src_ds01 = None
src_ds02 = None

In [66]:
type(src01_ar)

numpy.ndarray

In [67]:
type(src02_ar)

numpy.ndarray

In [68]:
src01_ar

array([[ 270.55001831,  270.55001831,  270.55001831, ...,  270.55001831,
         270.55001831,  270.55001831],
       [ 270.55001831,  270.55001831,  270.55001831, ...,  270.55001831,
         270.55001831,  270.55001831],
       [ 270.55001831,  270.55001831,  270.55001831, ...,  270.55001831,
         270.55001831,  270.55001831],
       ..., 
       [ 218.55000305,  218.55000305,  218.55000305, ...,  218.55000305,
         218.55000305,  218.55000305],
       [ 219.3500061 ,  219.3500061 ,  219.3500061 , ...,  219.3500061 ,
         219.3500061 ,  219.3500061 ],
       [ 219.75001526,  219.75001526,  219.75001526, ...,  219.75001526,
         219.75001526,  219.75001526]], dtype=float32)

In [69]:
src02_ar

array([[ 269.8500061 ,  269.8500061 ,  269.8500061 , ...,  269.8500061 ,
         269.8500061 ,  269.8500061 ],
       [ 269.95001221,  269.95001221,  269.95001221, ...,  269.95001221,
         269.95001221,  269.95001221],
       [ 269.95001221,  269.95001221,  270.05001831, ...,  269.95001221,
         269.95001221,  269.95001221],
       ..., 
       [ 218.25001526,  218.25001526,  218.25001526, ...,  218.25001526,
         218.25001526,  218.25001526],
       [ 218.95001221,  218.95001221,  218.95001221, ...,  218.95001221,
         218.95001221,  218.95001221],
       [ 219.45001221,  219.45001221,  219.45001221, ...,  219.45001221,
         219.45001221,  219.45001221]], dtype=float32)

Operating with bands as NumPy arrays:

In [70]:
res = (src01_ar -273.15) - (src02_ar -273.15)

In [71]:
type(res)

numpy.ndarray

In [72]:
res

array([[ 0.70001221,  0.70001221,  0.70001221, ...,  0.70001221,
         0.70001221,  0.70001221],
       [ 0.6000061 ,  0.6000061 ,  0.6000061 , ...,  0.6000061 ,
         0.6000061 ,  0.6000061 ],
       [ 0.6000061 ,  0.6000061 ,  0.5       , ...,  0.6000061 ,
         0.6000061 ,  0.6000061 ],
       ..., 
       [ 0.29998779,  0.29998779,  0.29998779, ...,  0.29998779,
         0.29998779,  0.29998779],
       [ 0.3999939 ,  0.3999939 ,  0.3999939 , ...,  0.3999939 ,
         0.3999939 ,  0.3999939 ],
       [ 0.30000305,  0.30000305,  0.30000305, ...,  0.30000305,
         0.30000305,  0.30000305]], dtype=float32)

Store NumPy array result on a new raster dataset:

In [73]:
dst_file = '/tmp/out_mapalgebra_gdal.tif'

drv_gtif = gdal.GetDriverByName("GTiff")
src_ds = gdal.Open(src_file01)

In [74]:
src_geot = src_ds.GetGeoTransform()

x_sz = src_ds.RasterXSize
y_sz = src_ds.RasterYSize

print(src_geot)
print(x_sz, y_sz)

(-180.0, 0.25, 0.0, 90.0, 0.0, -0.2498266296809986)
1440 721


In [75]:
datatype = gdal.GDT_Float32
n_band = 1
nodata_val = -99999

dst_raster = drv_gtif.Create(dst_file, x_sz, y_sz, n_band, datatype)
dst_raster.SetGeoTransform(src_geot)

0

Write NumPy results

In [76]:
out_band = dst_raster.GetRasterBand(n_band)
out_band.SetNoDataValue(nodata_val)
out_band.WriteArray(res)

0

Close datasets:

In [77]:
src_ds = None
dst_raster = None