This notebook was prepared by Cayetano Benavent, 2016.

# NumPy 01 - Handling arrays

Importing library (convention):

In [20]:
import numpy as np

## Array creation:

In [21]:
a = np.array([1,2,3,4])

In [22]:
type(a)

numpy.ndarray

Number of dimensions and size:

In [23]:
a.ndim

1

In [24]:
a.size

4

Array shape:

In [25]:
a.shape

(4,)

Reshape an array (1 Dimension to 2 Dimensions):

In [26]:
a2 = a.reshape((2,2))

In [27]:
a2

array([[1, 2],
       [3, 4]])

In [28]:
a2.shape

(2, 2)

In [29]:
a2.size

4

In [30]:
a2.ndim

2

Array creation from range:

In [31]:
b = np.arange(54)

In [32]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

In [33]:
b.shape

(54,)

In [34]:
b.ndim

1

Create an array with evenly spaced numbers over a specified interval:

In [35]:
np.linspace(-20, 20, 101)

array([-20. , -19.6, -19.2, -18.8, -18.4, -18. , -17.6, -17.2, -16.8,
       -16.4, -16. , -15.6, -15.2, -14.8, -14.4, -14. , -13.6, -13.2,
       -12.8, -12.4, -12. , -11.6, -11.2, -10.8, -10.4, -10. ,  -9.6,
        -9.2,  -8.8,  -8.4,  -8. ,  -7.6,  -7.2,  -6.8,  -6.4,  -6. ,
        -5.6,  -5.2,  -4.8,  -4.4,  -4. ,  -3.6,  -3.2,  -2.8,  -2.4,
        -2. ,  -1.6,  -1.2,  -0.8,  -0.4,   0. ,   0.4,   0.8,   1.2,
         1.6,   2. ,   2.4,   2.8,   3.2,   3.6,   4. ,   4.4,   4.8,
         5.2,   5.6,   6. ,   6.4,   6.8,   7.2,   7.6,   8. ,   8.4,
         8.8,   9.2,   9.6,  10. ,  10.4,  10.8,  11.2,  11.6,  12. ,
        12.4,  12.8,  13.2,  13.6,  14. ,  14.4,  14.8,  15.2,  15.6,
        16. ,  16.4,  16.8,  17.2,  17.6,  18. ,  18.4,  18.8,  19.2,
        19.6,  20. ])

Reshape an array (1 Dimension to 4 Dimensions):

In [36]:
b2 = b.reshape((2,3,3,3))

In [37]:
b2

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [38]:
b2.ndim

4

Reshape an array (N Dimensions to 1 Dimension):

In [39]:
b2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

Creating arrays of zeros:

In [40]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Creating arrays of ones:

In [41]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Creating array of random numbers (PRNG):

In [42]:
np.random.rand(3,3)

array([[ 0.65111101,  0.92221781,  0.28751256],
       [ 0.95706407,  0.08355381,  0.93113247],
       [ 0.36235794,  0.40846132,  0.4121019 ]])

In [43]:
np.random.seed(111)

In [44]:
np.random.rand(3,3)

array([[ 0.61217018,  0.16906975,  0.43605902],
       [ 0.76926247,  0.2953253 ,  0.14916296],
       [ 0.02247832,  0.42022449,  0.23868214]])

In [45]:
np.random.seed(111)

In [46]:
np.random.rand(3,3)

array([[ 0.61217018,  0.16906975,  0.43605902],
       [ 0.76926247,  0.2953253 ,  0.14916296],
       [ 0.02247832,  0.42022449,  0.23868214]])

Creating a sample (or samples) from a normal distribution:

In [47]:
np.random.randn(3,3)

array([[-0.18384316, -0.11512978,  1.08784319],
       [ 1.52172568, -0.26208059, -1.75151683],
       [ 0.09137849,  0.12458097,  0.37108135]])

Creating a sample (or samples) from a normal distribution
defining mean, standard deviation and size:

In [48]:
np.random.normal?

In [49]:
np.random.normal(loc=50,scale=5,size=100)

array([ 52.00469631,  50.12063831,  50.7664686 ,  48.39489809,
        56.4007917 ,  49.78019896,  47.73528502,  52.93444712,
        58.88746287,  51.59213941,  45.00685284,  37.31608354,
        48.00155432,  45.44966872,  55.85141283,  41.75928902,
        45.47279955,  49.57454697,  56.96722487,  49.59600674,
        52.27132622,  51.21754229,  42.41397875,  47.80533921,
        47.80041833,  52.24410888,  45.70355354,  57.79712649,
        49.09917571,  46.66731106,  59.57921481,  45.30017734,
        61.67196829,  49.97683462,  54.54131908,  58.407208  ,
        54.21131987,  51.22234972,  48.91888187,  46.1506765 ,
        49.83990531,  43.03146011,  43.19383667,  43.3850918 ,
        49.42343635,  45.57786318,  51.88613717,  51.87154546,
        54.01013239,  55.23107712,  45.47600697,  43.65952864,
        52.59181742,  45.00235787,  46.72479554,  46.29169618,
        51.70042133,  53.8844131 ,  51.2513835 ,  56.22971067,
        43.46866115,  49.01539828,  53.32188097,  51.65

## Slicing arrays

In [50]:
c = np.arange(16).reshape((4,4))

In [51]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
c[1,1]

5

In [53]:
c[2,1]

9

In [54]:
c[2,2]

10

In [55]:
c[:,0]

array([ 0,  4,  8, 12])

In [56]:
c[:,1]

array([ 1,  5,  9, 13])

In [57]:
c[0]

array([0, 1, 2, 3])

In [58]:
c[0,:]

array([0, 1, 2, 3])

In [59]:
c[2:,2:]

array([[10, 11],
       [14, 15]])

In [60]:
c[::2,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [61]:
c[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

## Copies and views

d array is a view and e array is a copy:

In [62]:
d = c[2:,2:]
e = c[2:,2:].copy()

In [63]:
d

array([[10, 11],
       [14, 15]])

In [64]:
c[-1,-1]

15

In [65]:
c[-1,-1] = 500

In [66]:
c

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14, 500]])

In [67]:
d

array([[ 10,  11],
       [ 14, 500]])

In [68]:
e

array([[10, 11],
       [14, 15]])