This notebook was prepared by Cayetano Benavent, 2016.

# NumPy 01 - Handling arrays

Importing library (convention):

In [188]:
import numpy as np

## Array creation:

In [189]:
a = np.array([1,2,3,4])

In [190]:
type(a)

numpy.ndarray

Number of dimensions and size:

In [191]:
a.ndim

1

In [192]:
a.size

4

Array shape:

In [193]:
a.shape

(4,)

Reshape an array (1 Dimension to 2 Dimensions):

In [194]:
a2 = a.reshape((2,2))

In [195]:
a2

array([[1, 2],
       [3, 4]])

In [196]:
a2.shape

(2, 2)

In [197]:
a2.size

4

In [198]:
a2.ndim

2

Array creation from range:

In [199]:
b = np.arange(54)

In [200]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

In [201]:
b.shape

(54,)

In [202]:
b.ndim

1

Reshape an array (1 Dimension to 4 Dimensions):

In [203]:
b2 = b.reshape((2,3,3,3))

In [204]:
b2

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [205]:
b2.ndim

4

Creating arrays of zeros:

In [206]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Creating arrays of ones:

In [207]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Creating array of random numbers (PRNG):

In [208]:
np.random.rand(3,3)

array([[ 0.41247483,  0.92583386,  0.82538045],
       [ 0.50102967,  0.11678892,  0.01159232],
       [ 0.91315044,  0.51239748,  0.84308211]])

In [209]:
np.random.seed(111)

In [210]:
np.random.rand(3,3)

array([[ 0.61217018,  0.16906975,  0.43605902],
       [ 0.76926247,  0.2953253 ,  0.14916296],
       [ 0.02247832,  0.42022449,  0.23868214]])

In [211]:
np.random.seed(111)

In [212]:
np.random.rand(3,3)

array([[ 0.61217018,  0.16906975,  0.43605902],
       [ 0.76926247,  0.2953253 ,  0.14916296],
       [ 0.02247832,  0.42022449,  0.23868214]])

Creating a sample (or samples) from a normal distribution:

In [213]:
np.random.randn(3,3)

array([[-0.18384316, -0.11512978,  1.08784319],
       [ 1.52172568, -0.26208059, -1.75151683],
       [ 0.09137849,  0.12458097,  0.37108135]])

Creating a sample (or samples) from a normal distribution
defining mean, standard deviation and size:

In [214]:
np.random.normal?

In [215]:
np.random.normal(loc=50,scale=5,size=100)

array([ 52.00469631,  50.12063831,  50.7664686 ,  48.39489809,
        56.4007917 ,  49.78019896,  47.73528502,  52.93444712,
        58.88746287,  51.59213941,  45.00685284,  37.31608354,
        48.00155432,  45.44966872,  55.85141283,  41.75928902,
        45.47279955,  49.57454697,  56.96722487,  49.59600674,
        52.27132622,  51.21754229,  42.41397875,  47.80533921,
        47.80041833,  52.24410888,  45.70355354,  57.79712649,
        49.09917571,  46.66731106,  59.57921481,  45.30017734,
        61.67196829,  49.97683462,  54.54131908,  58.407208  ,
        54.21131987,  51.22234972,  48.91888187,  46.1506765 ,
        49.83990531,  43.03146011,  43.19383667,  43.3850918 ,
        49.42343635,  45.57786318,  51.88613717,  51.87154546,
        54.01013239,  55.23107712,  45.47600697,  43.65952864,
        52.59181742,  45.00235787,  46.72479554,  46.29169618,
        51.70042133,  53.8844131 ,  51.2513835 ,  56.22971067,
        43.46866115,  49.01539828,  53.32188097,  51.65

## Slicing arrays

In [216]:
c = np.arange(16).reshape((4,4))

In [217]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [218]:
c[1,1]

5

In [219]:
c[2,1]

9

In [220]:
c[2,2]

10

In [221]:
c[:,0]

array([ 0,  4,  8, 12])

In [222]:
c[:,1]

array([ 1,  5,  9, 13])

In [223]:
c[0]

array([0, 1, 2, 3])

In [224]:
c[0,:]

array([0, 1, 2, 3])

In [225]:
c[2:,2:]

array([[10, 11],
       [14, 15]])

In [226]:
c[::2,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [227]:
c[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

## Copies and views

d array is a view and e array is a copy:

In [228]:
d = c[2:,2:]
e = c[2:,2:].copy()

In [229]:
d

array([[10, 11],
       [14, 15]])

In [230]:
c[-1,-1]

15

In [231]:
c[-1,-1] = 500

In [232]:
c

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14, 500]])

In [233]:
d

array([[ 10,  11],
       [ 14, 500]])

In [234]:
e

array([[10, 11],
       [14, 15]])