This notebook was prepared by Cayetano Benavent, 2016.

# NumPy 02 - operations with arrays

## Array elementwise operations

In [94]:
import numpy as np

In [95]:
c = np.arange(16).reshape((4,4))

In [96]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
c * 5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75]])

In [98]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
h = (c * 5) + 10

In [100]:
h

array([[10, 15, 20, 25],
       [30, 35, 40, 45],
       [50, 55, 60, 65],
       [70, 75, 80, 85]])

## Operations with arrays and fancy indexing:

In [101]:
h < 20

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [102]:
h[h < 20] = 200

In [103]:
h

array([[200, 200,  20,  25],
       [ 30,  35,  40,  45],
       [ 50,  55,  60,  65],
       [ 70,  75,  80,  85]])

In [104]:
h[h >= 75] * -1

array([-200, -200,  -75,  -80,  -85])

In [105]:
h

array([[200, 200,  20,  25],
       [ 30,  35,  40,  45],
       [ 50,  55,  60,  65],
       [ 70,  75,  80,  85]])

In [106]:
h[h >= 75] = h[h >= 75] * -1

In [107]:
h

array([[-200, -200,   20,   25],
       [  30,   35,   40,   45],
       [  50,   55,   60,   65],
       [  70,  -75,  -80,  -85]])

## Reductions

In [108]:
h.max()

70

In [109]:
h.min()

-200

In [110]:
h.sum()

-145

In [111]:
h.sum(axis=0)

array([ -50, -185,   40,   50])

In [112]:
h.sum(axis=1)

array([-355,  150,  230, -170])

In [113]:
h.mean()

-9.0625

In [114]:
h.std()

87.664465969684656

## Broadcasting

In [115]:
i = np.arange(6).reshape((2,3))
j = np.arange(3)

In [116]:
i

array([[0, 1, 2],
       [3, 4, 5]])

In [117]:
j

array([0, 1, 2])

In [118]:
i + j

array([[0, 2, 4],
       [3, 5, 7]])

## Array multiplication (element wise) and matrix multiplication

In [121]:
a = np.arange(9).reshape((3,3))

In [122]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
n = np.ones((3,3),dtype=int)

In [130]:
n

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Elementwise product:

In [131]:
a * n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Matrix product:

In [132]:
a.dot(n)

array([[ 3,  3,  3],
       [12, 12, 12],
       [21, 21, 21]])